name: 💡 Feature request
description: Suggest an idea for this project
title: "<title>"
labels: []
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please, search to see if an issue already exists for the bug you encountered.
    options:
      - label: I have checked this issue does not exist yet.
        required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: Please, describe the problem... i.e. "I'm always frustrated when [...]"
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you would like
    description: Detail your idea and any alternatives or features you have considered.
    If you already know how your feature could be implemented, give us some guidance.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false